### ISSUE TITLE
The keyword as is not highlighted

### ISSUE THREAD

**Issue by edalorzo** [seanjames777/SML-Language-Definition#10]
For instance, in a binary tree definition like the following:

datatype 'label btree= 
    Empty
  | Node of 'label \* 'label btree \* 'label btree

And then I have method insert as follows:

fun insert(x, Empty) = Node(x, Empty, Empty)
  | insert(x, T as Node(y, left, right)) = 
        if lt(x,y) then Node(y, insert(x, left), right)
        else if lt(y,x) then Node(y, left, insert(x, right))
        else (_x=y_) T (_do nothin; x was already there_)

The keyword "as" is not highlighted.

**Comment by seanjames777** [comment]
Fixed, thanks.

**Comment by edalorzo** [comment]
Thank you for your work. Your plugin is awesome. I use it all the time.

**Comment by seanjames777** [comment]
=D Thanks!
