### ISSUE TITLE
Missing Keywords

### ISSUE THREAD

**Issue by edalorzo** [seanjames777/SML-Language-Definition#11]
I went over The Definition of Standard ML in the section Reserved Words (section 2.1) and I noticed several keywords not currently supported in the current definition of this project (at least the version I am using):

abstype
do
infix
infixr
nonfix
op
rec
with
withtype
while

You can download the 1990 revision by Milner from this site:
http://www.itu.dk/people/tofte/publ/1990sml/1990sml.html

Or you can brows the Kindle edition for the revision of 1997:
http://www.amazon.com/The-Definition-Standard-ML-ebook/dp/B004LRPUVC/ref=tmm_kin_title_0

In the kindle preview you can see the keywords for the language.

I hope this helps!

**Comment by edalorzo** [comment]
By the way, later, section 3.1 Reserved Words, has a set of additional reserved words that can be added here. From those the following are missing:

eqtype
include
sharing

**Comment by seanjames777** [comment]
Fixed, thanks.

**Comment by edalorzo** [comment]
b(^_^)d
